# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GruposPred',
            fields=[
                ('IDgrupo', models.AutoField(primary_key=True, serialize=False)),
                ('encargado', models.CharField(max_length=50)),
                ('auxiliar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('Idinf', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.IntegerField()),
                ('publicaciones', models.IntegerField()),
                ('videos', models.IntegerField()),
                ('revisitas', models.IntegerField()),
                ('estudios', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Precursor',
            fields=[
                ('IDprecursor', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publicador',
            fields=[
                ('IDpub', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('fechaBau', models.CharField(max_length=10, verbose_name='Fecha de Bautismo')),
                ('fechaNa', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('FKgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretario.GruposPred')),
            ],
        ),
        migrations.CreateModel(
            name='PubPrecursor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('mesIni', models.IntegerField()),
                ('yearIni', models.IntegerField()),
                ('status', models.BooleanField()),
                ('FKprecursor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretario.Precursor')),
                ('FKpub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretario.Publicador')),
            ],
        ),
        migrations.AddField(
            model_name='publicador',
            name='precursorado',
            field=models.ManyToManyField(through='secretario.PubPrecursor', to='secretario.Precursor'),
        ),
        migrations.AddField(
            model_name='informe',
            name='FKpub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretario.Publicador'),
        ),
    ]
