# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peridoprecursor',
            name='FKprecursor',
        ),
        migrations.RemoveField(
            model_name='peridoprecursor',
            name='FKpub',
        ),
        migrations.DeleteModel(
            name='PeridoPrecursor',
        ),
    ]
