# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0002_auto_20160330_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubprecursor',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
