# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0003_remove_infopub_fkpub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopub',
            name='FKinf',
        ),
        migrations.DeleteModel(
            name='InfoPub',
        ),
    ]
