# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0003_nroprec'),
    ]

    operations = [
        migrations.CreateModel(
            name='horasCon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('horas', models.IntegerField()),
                ('FKpub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretario.Publicador')),
            ],
        ),
        migrations.CreateModel(
            name='privilegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('edadMin', models.IntegerField(verbose_name='Edad minima')),
                ('tiempoBauMin', models.IntegerField(verbose_name='Tiempo minimo de bautizado')),
            ],
        ),
        migrations.CreateModel(
            name='privilegioPub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='mes de nombramiento')),
                ('year', models.IntegerField(verbose_name='anio de nombramiento')),
                ('FKpriv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretario.privilegio')),
                ('FKpub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretario.Publicador')),
            ],
        ),
        migrations.AddField(
            model_name='publicador',
            name='privilegio',
            field=models.ManyToManyField(through='secretario.privilegioPub', to='secretario.privilegio'),
        ),
    ]
