# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0004_auto_20160301_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Informe',
        ),
    ]
