# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0005_delete_informe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('Idinf', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.IntegerField()),
                ('publicaciones', models.IntegerField()),
                ('videos', models.IntegerField()),
                ('revisitas', models.IntegerField()),
                ('estudios', models.IntegerField()),
                ('fecha', models.DateField()),
                ('FKpub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretario.Publicador')),
            ],
        ),
    ]
