# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0007_auto_20160314_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='fecha',
        ),
        migrations.AddField(
            model_name='informe',
            name='mes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
