# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0008_auto_20160328_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubprecursor',
            name='FKprecursor',
        ),
        migrations.RemoveField(
            model_name='pubprecursor',
            name='FKpub',
        ),
        migrations.AddField(
            model_name='publicador',
            name='precursorado',
            field=models.ManyToManyField(to='secretario.Precursor'),
        ),
    ]
