# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretario', '0009_privilegiopub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegiopub',
            name='fechaFin',
            field=models.CharField(default='activo', max_length=200),
            preserve_default=False,
        ),
    ]
