from django.conf.urls import url

from . import views

app_name="secretario"
urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^grupos/registrar/$', views.registrarGrupo, name='registrarGrupo'),
    url(r'^registrar/grupos/$', views.grupos_registrar, name='grupos_registrar'),
    url(r'^consultar/grupos/$', views.conGrupo, name='conGrupo'),
    url(r'^(?P<idGrupo>[0-9]+)/grupoPublicador/$', views.conGrupoofPubs, name='conGrupoofPubs'),
    url(r'^(?P<idGrupo>[0-9]+)/datos_grupo/$', views.datGrupo, name='datGrupo'),
    url(r'^regPubli/$', views.regPubli, name='regPubli'),
    url(r'^conPub/$', views.conPub, name='conPub'),
    url(r'^publicreg/$', views.publicReg, name='publicReg'),
    url(r'^cambiarpub/$', views.cambiarPub, name='cambiarPub'),
    url(r'^consultar/Publicadores/$', views.conPubs, name='conPubs'),
    url(r'^(?P<idpub>[0-9]+)/Publicador/$', views.traerPub, name='traerPub'),
	url(r'^modGrup/$', views.modGrup, name='modGrup'),
    url(r'^informe/registrar/$', views.viewInfo, name='viewInfo'),
	url(r'^regInf/$', views.regInf, name='regInf'),
	url(r'^(?P<vista>[1-2]+)/(?P<idPub>[0-9]+)/Tarjeta/(?P<y>[0-9]+)/$', views.tarjeta, name='tarjeta'),
	url(r'^conPubG/$', views.conPubG, name='conPubG'),
	url(r'^Publicador/verTarjeta$', views.verTarjetaPub, name='verTarjetaPub'),
    url(r'^Precursores/horas/$', views.editPrecur, name='editPrecur'),
    url(r'^Precursores/nombrar/$', views.vistaNombrar, name='vistaNombrar'),
    url(r'^nombrar/$', views.NombrarPrecur, name='NombrarPrecur'),
    url(r'^modPub/$', views.modPub, name='modPub'),
    url(r'^consultar/Precursor/$', views.conPrec, name='conPrec'),
    url(r'^conPrecs/$', views.conPrecs, name='conPrecs'),
    url(r'^historia/precursor/(?P<year>[a-zA-Z0-9]+)/$', views.historiaPrec, name='historiaPrec'),
    url(r'^conYear/$', views.yearServicio, name='yearServicio'),
    url(r'^darBaja/$', views.darBaja, name='darBaja'),
    url(r'^registrar/usuario/$', views.usuReg, name='usuReg'),
    url(r'^regusu/$', views.Regusu, name='Regusu'),
    url(r'^estadisticas/$', views.estadisticas, name='estadisticas'),
    url(r'^estadisticas/informeGeneral', views.infG, name='infG'),
    url(r'^estadisticas/Precurs', views.infPrec, name='infPrec'),
    url(r'^PrecursInf', views.conInfPrec, name='conInfPrec'),
    url(r'^estadisticas/Publicador', views.estPub, name='estPub'),
    url(r'^pubEst', views.conEstPub, name='conEstPub'),
    url(r'^estadisticas/global', views.estGlobal, name='estGlobal'),
    url(r'^pdf/tarjeta/publicador', views.vistaPdfPub, name='vistaPdfPub'),
    url(r'^pdfTarPub', views.datosPdfPub, name='datosPdfPub'),
]